-- 039: a reference every machine has, and two stages that were misread.
--
-- THE REFERENCE. asset_ref was generated by the registration endpoint, which
-- is fine while every machine arrives through the form. The spreadsheet import
-- inserted rows directly and never called next_asset_ref(), so 129 of 130
-- machines have no number — the one thing the register exists to give them.
--
-- Making the endpoint remember is not the fix, because the next importer will
-- forget in the same way. The column gets a default, so a row cannot be
-- written without one whatever path it came in by.
--
-- THE TWO STAGES. The import read a status column and matched "off road"
-- anywhere in it. Two entries said something different:
--
--     "To be done Off Road"      a plan, not a state — it is still working
--     "Off Road/ Running B/D"    running, with a breakdown
--
-- Both were filed as OFF_ROAD, and the register's default view hides off-road
-- machines, so the two tippers the entry operator was looking for had
-- disappeared from the list. A wrong status that also hides the row is worse
-- than a wrong status, because nobody can go and correct it.

-- ── the reference ────────────────────────────────────────────────────────────
ALTER TABLE asset ALTER COLUMN asset_ref SET DEFAULT next_asset_ref();

COMMENT ON COLUMN asset.asset_ref IS
    'EQP-YYYY-NNNN, this platform''s own name for the machine. Defaulted at the '
    'column so no insert path can produce a machine without one — the import '
    'did exactly that and left 129 machines unnumbered.';

-- Backfill, oldest first so the numbers follow the order machines were
-- registered rather than the order the rows happen to sit in.
DO $$
DECLARE
    row_to_number record;
BEGIN
    FOR row_to_number IN
        SELECT asset_id FROM asset WHERE asset_ref IS NULL
        ORDER BY created_at, asset_id
    LOOP
        UPDATE asset SET asset_ref = next_asset_ref()
         WHERE asset_id = row_to_number.asset_id;
    END LOOP;
END $$;

-- ── the misread stages ───────────────────────────────────────────────────────
-- "To be done" is a plan. The machine is still working until somebody says
-- otherwise, and saying otherwise is now something the register can do.
UPDATE asset a SET status = 'ACTIVE'
  FROM asset_lifecycle l
 WHERE l.asset_id = a.asset_id
   AND l.ended_on IS NULL
   AND a.status = 'OFF_ROAD'
   AND l.reason ~* 'to be (done|made)';

UPDATE asset_lifecycle SET stage = 'ACTIVE',
       reason = reason || ' — read as a plan rather than a state; corrected in 039'
 WHERE ended_on IS NULL
   AND stage = 'OFF_ROAD'
   AND reason ~* 'to be (done|made)';

-- "Off Road/ Running B/D" says running with a breakdown, which is the
-- workshop rather than the end of the road.
UPDATE asset a SET status = 'MAINTENANCE'
  FROM asset_lifecycle l
 WHERE l.asset_id = a.asset_id
   AND l.ended_on IS NULL
   AND a.status = 'OFF_ROAD'
   AND l.reason ~* 'running\s*b/?d';

UPDATE asset_lifecycle SET stage = 'MAINTENANCE',
       reason = reason || ' — running with a breakdown is the workshop, not off road; corrected in 039'
 WHERE ended_on IS NULL
   AND stage = 'OFF_ROAD'
   AND reason ~* 'running\s*b/?d';
